# Generated by Django 5.1.7 on 2025-04-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='birth_date',
            new_name='date_of_birth',
        ),
    ]
